title: "Kliment Dukovski"
description: "Cryptocurrency, investing, finance, and technical writing by Kliment Dukovski."
url: "https://kliment-dukovski.github.io"
baseurl: ""
social_image: "/assets/images/profile.png"

permalink: /articles/:slug/

author:
  name: "Kliment Dukovski"
  url: "https://kliment-dukovski.github.io/"
  image: "/assets/images/profile.png"
  job_title: "Cryptocurrency and Investments Writer"
  description: "Cryptocurrency and investments writer with more than 11 years of experience."
  same_as:
    - "https://medium.com/@dukovski.kliment"
    - "https://www.linkedin.com/in/klimentdukovski/"
    - "https://x.com/KlimentDuke"
    - "https://www.finder.com/author/klimentdukovski"
    - "https://finbold.com/author/kliment/"
    - "https://www.amazon.com/stores/Kliment-Dukovski/author/B00S169ENY?"

markdown: kramdown

paginate: 12
paginate_path: "/articles/page:num/"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

defaults:
  - scope:
      path: "google54c011f00fde185c.html"
    values:
      sitemap: false
